self-call.p4(17): error: c: Cannot refer to control inside itself
    c() c_inst;
    ^
